<?php

use Illuminate\Database\Seeder;

class AccountsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $accounts = [
            [
                'code' => 'ACC0000001',
                'name' => 'Cash',
                'short_name' => 'Cash',
                'notes' => 'Outstanding invoices the company has issued out to the client but has not yet received in cash at balance date.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 1,
                'account_category_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000002',
                'name' => 'Bank',
                'short_name' => 'Bank',
                'notes' => 'Outstanding invoices the company has issued out to the client but has not yet received in cash at balance date.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 2,
                'account_category_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000003',
                'name' => 'Accounts Receivable',
                'short_name' => 'Accounts Receivable',
                'notes' => 'Outstanding invoices the company has issued out to the client but has not yet received in cash at balance date.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 3,
                'account_category_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000004',
                'name' => 'Computer Equipment',
                'short_name' => 'Computer Equipment',
                'notes' => 'Computer equipment that is owned and controlled by the business.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 4,
                'account_category_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000005',
                'name' => 'Inventory',
                'short_name' => 'Inventory',
                'notes' => 'Value of tracked items for resale.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 5,
                'account_category_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000006',
                'name' => 'Office Equipment',
                'short_name' => 'Office Equipment',
                'notes' => 'Office equipment that is owned and controlled by the business.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 4,
                'account_category_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000007',
                'name' => 'Prepayments',
                'short_name' => 'Prepayments',
                'notes' => 'An expenditure that has been paid for in advance.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 3,
                'account_category_id' => 1,
                'company_id' => 1,
            ],
            /** END ASSETS ACCOUNTS */

            [
                'code' => 'ACC0000008',
                'name' => 'Accounts Payable ',
                'short_name' => 'Accounts Payable',
                'notes' => 'Outstanding invoices the company has received from suppliers but has not yet paid at balance date.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000009',
                'name' => 'Unpaid Expense Claims',
                'short_name' => 'Unpaid Expense Claims',
                'notes' => 'Expense claims typically made by employees/shareholder employees still outstanding.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000010',
                'name' => 'Wages Payable',
                'short_name' => 'Wages Payable',
                'notes' => 'System automatically updates this account for payroll entries created using Payroll and will store the payroll amount to be paid to the employee for the pay run.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000011',
                'name' => 'Sales Tax',
                'short_name' => 'Sales Tax',
                'notes' => 'The balance in this account represents Sales Tax owing to or from your tax authority.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000012',
                'name' => 'Employee Tax Payable',
                'short_name' => 'Employee Tax Payable',
                'notes' => 'The amount of tax that has been deducted from wages or salaries paid to employees and is due to be paid.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000013',
                'name' => 'Income Tax Payable',
                'short_name' => 'Income Tax Payable',
                'notes' => 'The amount of income tax that is due to be paid, also resident withholding tax paid on interest received.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000014',
                'name' => 'Owners Drawings',
                'short_name' => 'Owners Drawings',
                'notes' => 'Withdrawals by the owners.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000015',
                'name' => 'Owners Funds Introduced',
                'short_name' => 'Owners Funds Introduced',
                'notes' => 'Funds contributed by the owner.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 8,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000016',
                'name' => 'Loan',
                'short_name' => 'Loan',
                'notes' => 'Money that has been borrowed from a creditor',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 10,
                'account_category_id' => 2,
                'company_id' => 1,
            ],
            /** END LIABILITY ACCOUNTS */

            [
                'code' => 'ACC0000017',
                'name' => 'Retained Earnings',
                'short_name' => 'Retained Earnings',
                'notes' => 'The retained earnings of a corporation is the accumulated net income of the corporation that is retained by the corporation at a particular point of time, such as at the end of the reporting period.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 18,
                'account_category_id' => 5,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000018',
                'name' => 'Owners Share Capital',
                'short_name' => 'Owners Share Capital',
                'notes' => 'The value of shares purchased by the shareholders.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 18,
                'account_category_id' => 5,
                'company_id' => 1,
            ],
            /** END EQUITY ACCOUNTS */

            [
                'code' => 'ACC0000019',
                'name' => 'Cost of Goods Sold',
                'short_name' => 'Cost of Goods Sold',
                'notes' => 'Cost of goods sold by the business.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 15,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000020',
                'name' => 'Advertising',
                'short_name' => 'Advertising',
                'notes' => 'Expenses incurred for advertising while trying to increase sales.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000021',
                'name' => 'Bank Fees',
                'short_name' => 'Bank Fees',
                'notes' => 'Fees charged by your bank for transactions regarding your bank account(s).',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000022',
                'name' => 'Cleaning',
                'short_name' => 'Cleaning',
                'notes' => 'Expenses incurred for cleaning business property.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000023',
                'name' => 'Consulting & Accounting ',
                'short_name' => 'Consulting & Accounting',
                'notes' => 'Expenses related to paying consultants.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000024',
                'name' => 'Depreciation',
                'short_name' => 'Depreciation',
                'notes' => 'The amount of the assets cost that was consumed during the period.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000025',
                'name' => 'Entertainment',
                'short_name' => 'Entertainment',
                'notes' => 'Expenses paid by company for the business but are not deductable for income tax purposes.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000026',
                'name' => 'Freight & Courier',
                'short_name' => 'Freight & Courier',
                'notes' => 'Expenses incurred on courier & freight costs.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000027',
                'name' => 'General Expenses ',
                'short_name' => 'General Expenses',
                'notes' => 'General expenses related to the running of the business.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000028',
                'name' => 'Insurance',
                'short_name' => 'Insurance',
                'notes' => 'Expenses incurred for insuring the business assets.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000029',
                'name' => 'Interest Expense',
                'short_name' => 'Interest Expense',
                'notes' => 'Any interest expenses paid to your tax authority, business bank accounts or credit card accounts.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000030',
                'name' => 'Legal expenses',
                'short_name' => 'Legal expenses',
                'notes' => 'Expenses incurred on any legal matters.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000031',
                'name' => 'Light, Power, Heating',
                'short_name' => 'Light, Power, Heating',
                'notes' => 'Expenses incurred for lighting, powering or heating the premises.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000032',
                'name' => 'Motor Vehicle Expenses',
                'short_name' => 'Motor Vehicle Expenses',
                'notes' => 'Expenses incurred on the running of company motor vehicles.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000033',
                'name' => 'Office Expenses',
                'short_name' => 'Office Expenses',
                'notes' => 'General expenses related to the running of the business office.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000034',
                'name' => 'Printing & Stationery',
                'short_name' => 'Printing & Stationery',
                'notes' => 'Expenses incurred by the entity as a result of printing and stationery.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000035',
                'name' => 'Rent',
                'short_name' => 'Rent',
                'notes' => 'The payment to lease a building or area.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000036',
                'name' => 'Payroll – Employer Share of Benefits',
                'short_name' => 'P-ESB',
                'notes' => 'Payroll – Employer Share of Benefits',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000037',
                'name' => 'Repairs and Maintenance',
                'short_name' => 'Repairs and Maintenance',
                'notes' => 'Expenses incurred on a damaged or run down asset that will bring the asset back to its original condition.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000038',
                'name' => 'Wages and Salaries',
                'short_name' => 'Wages and Salaries',
                'notes' => 'Payment to employees in exchange for their resources.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000039',
                'name' => 'Superannuation',
                'short_name' => 'Superannuation',
                'notes' => 'Superannuation contributions.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000040',
                'name' => 'Subscriptions',
                'short_name' => 'Subscriptions',
                'notes' => 'E.g. Magazines, professional bodies.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000041',
                'name' => 'Telephone & Internet',
                'short_name' => 'Telephone & Internet',
                'notes' => 'Expenditure incurred from any business-related phone calls, phone lines, or internet connections.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000042',
                'name' => 'Travel - National',
                'short_name' => 'Travel - National',
                'notes' => 'Expenses incurred from domestic travel which has a business purpose.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000043',
                'name' => 'Travel - International',
                'short_name' => 'Travel - International',
                'notes' => 'Expenses incurred from international travel which has a business purpose.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000044',
                'name' => 'Bank Revaluations',
                'short_name' => 'Bank Revaluations',
                'notes' => 'Bank account revaluations due for foreign exchange rate changes.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000045',
                'name' => 'Unrealised Currency Gains',
                'short_name' => 'Unrealised Currency Gains',
                'notes' => 'Unrealised currency gains on outstanding items.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000046',
                'name' => 'Realised Currency Gains',
                'short_name' => 'Realised Currency Gains',
                'notes' => 'Gains or losses made due to currency exchange rate changes.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000047',
                'name' => 'Income Tax Expense',
                'short_name' => 'Income Tax Expense',
                'notes' => 'A percentage of total earnings paid to the government.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 16,
                'account_category_id' => 4,
                'company_id' => 1,
            ],
            /** END EXPENSE ACCOUNTS */

            [
                'code' => 'ACC0000048',
                'name' => 'Sales',
                'short_name' => 'Sales',
                'notes' => 'Income from any normal business activity.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 11,
                'account_category_id' => 3,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000049',
                'name' => 'Other Income',
                'short_name' => 'Other Income',
                'notes' => 'Any other income that does not relate to normal business activities and is not recurring.',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 11,
                'account_category_id' => 3,
                'company_id' => 1,
            ],
            [
                'code' => 'ACC0000050',
                'name' => 'Cheques in Hand',
                'short_name' => 'CIH',
                'notes' => 'Cheques in Hand',
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'account_type_id' => 3,
                'account_category_id' => 1,
                'company_id' => 1,
            ]
            /** END INCOME ACCOUNTS */

        ];
        $now = \Carbon\Carbon::now();
        foreach ($accounts as $key => $account) {
            $accounts[$key]['created_at'] = $now;
            $accounts[$key]['updated_at'] = $now;
        }
        \App\Account::insert($accounts);
    }
}
