<?php

use Illuminate\Database\Seeder;

class ExpensepaymentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $expensepayments = [
            [
                'payment' => 55.55,
                'payment_date' => \Carbon\Carbon::now()->subDays(7),
                'payment_mode' => 'Cash',
                'cheque_no' => '987654',
                'cheque_date' => \Carbon\Carbon::now()->subDays(7),
                'account_no' => '9876543210',
                'deposited_date' => \Carbon\Carbon::now()->subDays(6),
                'card_holder_name' => 'Emily White',
                'card_no' => 9999888877776666,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(5),
                'bank_id' => 5,
                'status' => 'Paid',
                'notes' => 'First Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 1,
                'expense_id' => 1,
                'company_id' => 2,
            ],
            [
                'payment' => 60.60,
                'payment_date' => \Carbon\Carbon::now()->subDays(8),
                'payment_mode' => 'Bank',
                'cheque_no' => '987653',
                'cheque_date' => \Carbon\Carbon::now()->subDays(8),
                'account_no' => '9876543211',
                'deposited_date' => \Carbon\Carbon::now()->subDays(7),
                'card_holder_name' => 'John Doe',
                'card_no' => 1111222233334444,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(6),
                'bank_id' => 6,
                'status' => 'Canceled',
                'notes' => 'Second Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 2,
                'expense_id' => 2,
                'company_id' => 2,
            ],
            [
                'payment' => 70.70,
                'payment_date' => \Carbon\Carbon::now()->subDays(9),
                'payment_mode' => 'Own Cheque',
                'cheque_no' => '987652',
                'cheque_date' => \Carbon\Carbon::now()->subDays(9),
                'account_no' => '9876543212',
                'deposited_date' => \Carbon\Carbon::now()->subDays(8),
                'card_holder_name' => 'Alice Johnson',
                'card_no' => 2222333344445555,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(7),
                'bank_id' => 7,
                'status' => 'Paid',
                'notes' => 'Third Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 3,
                'expense_id' => 3,
                'company_id' => 2,
            ],
            [
                'payment' => 80.80,
                'payment_date' => \Carbon\Carbon::now()->subDays(10),
                'payment_mode' => 'Cash',
                'cheque_no' => '987651',
                'cheque_date' => \Carbon\Carbon::now()->subDays(10),
                'account_no' => '9876543213',
                'deposited_date' => \Carbon\Carbon::now()->subDays(9),
                'card_holder_name' => 'Bob Smith',
                'card_no' => 3333444455556666,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(8),
                'bank_id' => 8,
                'status' => 'Canceled',
                'notes' => 'Fourth Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 3,
                'expense_id' => 4,
                'company_id' => 2,
            ],
            [
                'payment' => 90.90,
                'payment_date' => \Carbon\Carbon::now()->subDays(11),
                'payment_mode' => 'Cash',
                'cheque_no' => '987650',
                'cheque_date' => \Carbon\Carbon::now()->subDays(11),
                'account_no' => '9876543214',
                'deposited_date' => \Carbon\Carbon::now()->subDays(10),
                'card_holder_name' => 'Emma Brown',
                'card_no' => 4444555566667777,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(9),
                'bank_id' => 9,
                'status' => 'Paid',
                'notes' => 'Fifth Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 3,
                'expense_id' => 2,
                'company_id' => 2,
            ],
            [
                'payment' => 100.10,
                'payment_date' => \Carbon\Carbon::now()->subDays(12),
                'payment_mode' => 'Bank',
                'cheque_no' => '987649',
                'cheque_date' => \Carbon\Carbon::now()->subDays(12),
                'account_no' => '9876543215',
                'deposited_date' => \Carbon\Carbon::now()->subDays(11),
                'card_holder_name' => 'James Taylor',
                'card_no' => 5555666677778888,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(10),
                'bank_id' => 10,
                'status' => 'Canceled',
                'notes' => 'Sixth Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 2,
                'expense_id' => 2,
                'company_id' => 3,
            ],
            [
                'payment' => 110.11,
                'payment_date' => \Carbon\Carbon::now()->subDays(13),
                'payment_mode' => 'Own Cheque',
                'cheque_no' => '987648',
                'cheque_date' => \Carbon\Carbon::now()->subDays(13),
                'account_no' => '9876543216',
                'deposited_date' => \Carbon\Carbon::now()->subDays(12),
                'card_holder_name' => 'Sarah Miller',
                'card_no' => 6666777788889999,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(11),
                'bank_id' => 5,
                'status' => 'Paid',
                'notes' => 'Seventh Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 1,
                'expense_id' => 5,
                'company_id' => 2,
            ],
            [
                'payment' => 120.12,
                'payment_date' => \Carbon\Carbon::now()->subDays(14),
                'payment_mode' => 'Cash',
                'cheque_no' => '987647',
                'cheque_date' => \Carbon\Carbon::now()->subDays(14),
                'account_no' => '9876543217',
                'deposited_date' => \Carbon\Carbon::now()->subDays(13),
                'card_holder_name' => 'Michael Wilson',
                'card_no' => 7777888899990000,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(12),
                'bank_id' => 1,
                'status' => 'Paid',
                'notes' => 'Eighth Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 2,
                'expense_id' => 2,
                'company_id' => 1,
            ],
            [
                'payment' => 130.13,
                'payment_date' => \Carbon\Carbon::now()->subDays(15),
                'payment_mode' => 'Bank',
                'cheque_no' => '987646',
                'cheque_date' => \Carbon\Carbon::now()->subDays(15),
                'account_no' => '9876543218',
                'deposited_date' => \Carbon\Carbon::now()->subDays(14),
                'card_holder_name' => 'Olivia Davis',
                'card_no' => 8888999900001111,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(13),
                'bank_id' => 13,
                'status' => 'Canceled',
                'notes' => 'Ninth Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 2,
                'expense_id' => 4,
                'company_id' => 2,
            ],
            [
                'payment' => 140.14,
                'payment_date' => \Carbon\Carbon::now()->subDays(16),
                'payment_mode' => 'Bank',
                'cheque_no' => '987645',
                'cheque_date' => \Carbon\Carbon::now()->subDays(16),
                'account_no' => '9876543219',
                'deposited_date' => \Carbon\Carbon::now()->subDays(15),
                'card_holder_name' => 'Daniel Martinez',
                'card_no' => 9999000011112222,
                'expiry_date' => \Carbon\Carbon::now()->addMonths(14),
                'bank_id' => 14,
                'status' => 'Paid',
                'notes' => 'Tenth Expensepaymenets',
                'prepared_by' => 1,
                'paid_through' => 1,
                'expense_id' => 1,
                'company_id' => 2,
            ],
        ];
        $now = \Carbon\Carbon::now();
        foreach ($expensepayments as $key => $expensepayment) {
            $expensepayments[$key]['created_at'] = $now;
            $expensepayments[$key]['updated_at'] = $now;
        }

        \App\ExpensePayment::insert($expensepayments);
    }
}