<?php

use Illuminate\Database\Seeder;

class GrnitemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $grnitems = [
            [
                'quantity' => '100',
                'issued_qty' => '20',
                'pending_qty' => '80',
                'received_qty' => '100',
                'rejected_qty' => '35',
                'rate' => '440',
                'amount' => '4440',
                'manufacture_date' => '2024-01-01',
                'expiry_date' => '2024-04-01',
                'batch_no' => 'BA0001',
                'grade' => 'A',
                'color' => 'Blue',
                'packing_type' => 'RetailPacking',
                'brand' => 'Classic',
                'status' => 'Sent',
                'product_id' => 1,
                'grn_id' => 1,
            ],
            [
                'quantity' => '50',
                'issued_qty' => '10',
                'pending_qty' => '40',
                'received_qty' => '50',
                'rejected_qty' => '15',
                'rate' => '520',
                'amount' => '2600',
                'manufacture_date' => '2024-02-05',
                'expiry_date' => '2024-05-05',
                'batch_no' => 'BA0002',
                'grade' => 'B',
                'color' => 'Red',
                'packing_type' => 'Bulk Packaging',
                'brand' => 'Premium',
                'status' => 'Received',
                'product_id' => 2,
                'grn_id' => 2,
            ],
            // Additional arrays with random product_id and grn_id within the specified range
            [
                'quantity' => '80',
                'issued_qty' => '10',
                'pending_qty' => '70',
                'received_qty' => '80',
                'rejected_qty' => '25',
                'rate' => '360',
                'amount' => '2880',
                'manufacture_date' => '2024-03-10',
                'expiry_date' => '2024-06-10',
                'batch_no' => 'BA0003',
                'grade' => 'C',
                'color' => 'Green',
                'packing_type' => 'Flexible Packaging',
                'brand' => 'Eco',
                'status' => 'Sent',
                'product_id' => 3,
                'grn_id' => 3,
            ],
            [
                'quantity' => '60',
                'issued_qty' => '15',
                'pending_qty' => '45',
                'received_qty' => '60',
                'rejected_qty' => '10',
                'rate' => '380',
                'amount' => '2280',
                'manufacture_date' => '2024-01-15',
                'expiry_date' => '2024-04-15',
                'batch_no' => 'BA0004',
                'grade' => 'B',
                'color' => 'Yellow',
                'packing_type' => 'Drums and Barrels',
                'brand' => 'Standard',
                'status' => 'Received',
                'product_id' => 1,
                'grn_id' => 1,
            ],
            [
                'quantity' => '120',
                'issued_qty' => '25',
                'pending_qty' => '95',
                'received_qty' => '120',
                'rejected_qty' => '20',
                'rate' => '300',
                'amount' => '3600',
                'manufacture_date' => '2024-02-20',
                'expiry_date' => '2024-05-20',
                'batch_no' => 'BA0005',
                'grade' => 'A',
                'color' => 'White',
                'packing_type' => 'Cartons or Boxes',
                'brand' => 'Value',
                'status' => 'Sent',
                'product_id' => 2,
                'grn_id' => 2,
            ],
            [
                'quantity' => '75',
                'issued_qty' => '5',
                'pending_qty' => '70',
                'received_qty' => '75',
                'rejected_qty' => '15',
                'rate' => '420',
                'amount' => '3150',
                'manufacture_date' => '2024-03-05',
                'expiry_date' => '2024-06-05',
                'batch_no' => 'BA0006',
                'grade' => 'C',
                'color' => 'Black',
                'packing_type' => 'Shrink-Wrapping',
                'brand' => 'Essential',
                'status' => 'Received',
                'product_id' => 3,
                'grn_id' => 3,
            ],
            [
                'quantity' => '70',
                'issued_qty' => '15',
                'pending_qty' => '55',
                'received_qty' => '70',
                'rejected_qty' => '20',
                'rate' => '680',
                'amount' => '4760',
                'manufacture_date' => '2024-02-15',
                'expiry_date' => '2024-05-15',
                'batch_no' => 'BA0007',
                'grade' => 'A',
                'color' => 'White',
                'packing_type' => 'Cartons',
                'brand' => 'Superior',
                'status' => 'Damaged',
                'product_id' => 1,
                'grn_id' => 1,
            ],
            [
                'quantity' => '120',
                'issued_qty' => '30',
                'pending_qty' => '90',
                'received_qty' => '120',
                'rejected_qty' => '45',
                'rate' => '320',
                'amount' => '3840',
                'manufacture_date' => '2024-03-20',
                'expiry_date' => '2024-06-20',
                'batch_no' => 'BA0008',
                'grade' => 'B',
                'color' => 'Black',
                'packing_type' => 'Shrink-Wrapping',
                'brand' => 'Deluxe',
                'status' => 'Received',
                'product_id' => 2,
                'grn_id' => 2,
            ],
            [
                'quantity' => '150',
                'issued_qty' => '40',
                'pending_qty' => '110',
                'received_qty' => '150',
                'rejected_qty' => '30',
                'rate' => '580',
                'amount' => '8700',
                'manufacture_date' => '2024-04-25',
                'expiry_date' => '2024-07-25',
                'batch_no' => 'BA0009',
                'grade' => 'C',
                'color' => 'Yellow',
                'packing_type' => 'Drums',
                'brand' => 'Standard',
                'status' => 'Sent',
                'product_id' => 3,
                'grn_id' => 3,
            ],
            [
                'quantity' => '90',
                'issued_qty' => '25',
                'pending_qty' => '65',
                'received_qty' => '90',
                'rejected_qty' => '10',
                'rate' => '750',
                'amount' => '6750',
                'manufacture_date' => '2024-05-10',
                'expiry_date' => '2024-08-10',
                'batch_no' => 'BA0010',
                'grade' => 'A',
                'color' => 'Orange',
                'packing_type' => 'Cans',
                'brand' => 'Premium Plus',
                'status' => 'Received',
                'product_id' => 1,
                'grn_id' => 1,
            ],
        ];
        
$now = \Carbon\Carbon::now();
foreach ($grnitems as $key => $grnitem) {
    $grnitems[$key]['created_at'] = $now;
    $grnitems[$key]['updated_at'] = $now;
}
\App\GrnItem::insert($grnitems);
    }
}