<?php

use Illuminate\Database\Seeder;

class GrnsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $grns = [
            [
                'code' => 1,
                'date' => \Carbon\Carbon::now(),
                'grn_for' => 1,
                'notes' => 'Received goods in good condition.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 111222,
                'transport_name' => 'ABC Transports',
                'driver_name' => 'John Doe',
                'helper_name' => 'Jane Smith',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 1,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 2,
                'date' => \Carbon\Carbon::now()->subDays(1),
                'grn_for' => 1,
                'notes' => 'Checked and verified all items as per the purchase order.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 333444,
                'transport_name' => 'XYZ Logistics',
                'driver_name' => 'Michael Johnson',
                'helper_name' => 'Emily Brown',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 2,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 3,
                'date' => \Carbon\Carbon::now()->subDays(2),
                'grn_for' => 1,
                'notes' => 'Items were properly packaged and sealed.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 555666,
                'transport_name' => 'Quick Logistics',
                'driver_name' => 'Daniel Wilson',
                'helper_name' => 'Olivia Taylor',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 3,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 4,
                'date' => \Carbon\Carbon::now()->subDays(3),
                'grn_for' => 1,
                'notes' => 'All quantities match with the delivery note.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 777888,
                'transport_name' => 'Speedy Couriers',
                'driver_name' => 'Sophia Miller',
                'helper_name' => 'David Jones',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 4,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 5,
                'date' => \Carbon\Carbon::now()->subDays(4),
                'grn_for' => 1,
                'notes' => 'Checked for damages and defects; none found.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 999000,
                'transport_name' => 'Express Trans',
                'driver_name' => 'Emma Brown',
                'helper_name' => 'Jacob White',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 5,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 6,
                'date' => \Carbon\Carbon::now()->subDays(5),
                'grn_for' => 1,
                'notes' => 'Items were delivered ahead of schedule.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 121212,
                'transport_name' => 'Global Logistics',
                'driver_name' => 'Liam Wilson',
                'helper_name' => 'Ava Johnson',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 1,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 7,
                'date' => \Carbon\Carbon::now()->subDays(6),
                'grn_for' => 1,
                'notes' => 'Goods arrived securely packed and labeled.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 343434,
                'transport_name' => 'Swift Cargo',
                'driver_name' => 'Oliver Davis',
                'helper_name' => 'Sophie Taylor',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 2,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 8,
                'date' => \Carbon\Carbon::now()->subDays(7),
                'grn_for' => 1,
                'notes' => 'Received and confirmed all ordered items.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 565656,
                'transport_name' => 'Swift Freight',
                'driver_name' => 'Benjamin Wilson',
                'helper_name' => 'Charlotte Brown',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 3,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 9,
                'date' => \Carbon\Carbon::now()->subDays(8),
                'grn_for' => 1,
                'notes' => 'Verified and accepted the delivery.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 787878,
                'transport_name' => 'Fast Haulage',
                'driver_name' => 'Lucas Johnson',
                'helper_name' => 'Isabella Smith',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 4,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
            [
                'code' => 10,
                'date' => \Carbon\Carbon::now()->subDays(9),
                'grn_for' => 1,
                'notes' => 'Received the shipment without any issues.',
                'status' => 1,
                'transfer_by' => 1,
                'vehicle_id' => 1,
                'odo_starts_at' => \Carbon\Carbon::now(),
                'odo_ends_at' => \Carbon\Carbon::now(),
                'driver' => 1,
                'helper' => 1,
                'vehicle_no' => 909090,
                'transport_name' => 'Express Cargo',
                'driver_name' => 'Noah Davis',
                'helper_name' => 'Sophia Brown',
                'loaded_by' => 1,
                'unloaded_by' => 1,
                'trans_started_at' => \Carbon\Carbon::now(),
                'trans_ended_at' => \Carbon\Carbon::now(),
                'received_by' => 1,
                'parent_grn' => null,
                'purchase_order_id' => 5,
                'prepared_by' => 1,
                'production_unit_id' => 1,
                'store_id' => 1,
                'shop_id' => 1,
                'supplier_id' => 1,
                'company_id' => 1,
            ],
        ];
        

        $now = \Carbon\Carbon::now();
        foreach ($grns as $key => $add) {
            $grns[$key]['created_at'] = $now;
            $grns[$key]['updated_at'] = $now;
        }

        \App\Grn::insert($grns);
    }
}
