<?php

use Illuminate\Database\Seeder;

class InvoicepaymentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $invoicePayments = [
            [
                'payment' => 500.00,
                'payment_date' => '2024-02-01',
                'payment_type' => 'Advanced',
                'payment_mode' => 'Cash',
                'cheque_type' => 'Own',
                'cheque_no' => '',
                'cheque_date' => null,
                'is_cheque_realized' => null,
                'account_no' => null,
                'deposited_date' => null,
                'card_holder_name' => null,
                'card_no' => null,
                'expiry_date' => null,
                'bank_id' => 1,
                'status' => 'Paid',
                'notes' => 'Advance payment for invoice #INV001',
                'payment_from' => 'Direct',
                'refunded_from' => null,
                'credit_id' => null,
                'prepared_by' => 1,
                'deposited_to' => null,
                'invoice_id' => 1,
                'sales_order_id' => null,
                'customer_id' => 1,
                'business_type_id' => 1,
                'company_id' => 1,
                'sales_location_id' => 1,
                'uuid' => '123e4567-e89b-12d3-a456-426614174000',
            ],
            [
                'payment' => 1000.00,
                'payment_date' => '2024-02-05',
                'payment_type' => 'Partial Payment',
                'payment_mode' => 'Cheque',
                'cheque_type' => 'Own',
                'cheque_no' => 'CHQ12345',
                'cheque_date' => '2024-02-05',
                'is_cheque_realized' => 'No',
                'account_no' => null,
                'deposited_date' => null,
                'card_holder_name' => null,
                'card_no' => null,
                'expiry_date' => null,
                'bank_id' => 1,
                'status' => 'Paid',
                'notes' => 'Partial payment for invoice #INV002',
                'payment_from' => 'Direct',
                'refunded_from' => null,
                'credit_id' => null,
                'prepared_by' => 2,
                'deposited_to' => null,
                'invoice_id' => 2,
                'sales_order_id' => null,
                'customer_id' => 2,
                'business_type_id' => 1,
                'company_id' => 1,
                'sales_location_id' => 2,
                'uuid' => '123e4567-e89b-12d3-a456-426614174001',
            ],
            [
                'payment' => 500.00,
                'payment_date' => '2024-02-01',
                'payment_type' => 'Advanced',
                'payment_mode' => 'Cash',
                'cheque_type' => 'Own',
                'cheque_no' => '',
                'cheque_date' => null,
                'is_cheque_realized' => null,
                'account_no' => '',
                'deposited_date' => null,
                'card_holder_name' => '',
                'card_no' => '',
                'expiry_date' => null,
                'bank_id' => 1,
                'status' => 'Paid',
                'notes' => 'Advance payment for invoice #INV001',
                'payment_from' => 'Direct',
                'refunded_from' => null,
                'credit_id' => null,
                'prepared_by' => 1,
                'deposited_to' => null,
                'invoice_id' => 1,
                'sales_order_id' => null,
                'customer_id' => 1,
                'business_type_id' => 1,
                'company_id' => 1,
                'sales_location_id' => 1,
                'uuid' => '123e4567-e89b-12d3-a456-426614174000',
            ],
            [
                'payment' => 1000.00,
                'payment_date' => '2024-02-05',
                'payment_type' => 'Partial Payment',
                'payment_mode' => 'Cheque',
                'cheque_type' => 'Own',
                'cheque_no' => 'CHQ12345',
                'cheque_date' => '2024-02-05',
                'is_cheque_realized' => 'No',
                'account_no' => '',
                'deposited_date' => null,
                'card_holder_name' => '',
                'card_no' => '',
                'expiry_date' => null,
                'bank_id' => 1,
                'status' => 'Paid',
                'notes' => 'Partial payment for invoice #INV002',
                'payment_from' => 'Direct',
                'refunded_from' => null,
                'credit_id' => null,
                'prepared_by' => 2,
                'deposited_to' => null,
                'invoice_id' => 2,
                'sales_order_id' => null,
                'customer_id' => 2,
                'business_type_id' => 1,
                'company_id' => 1,
                'sales_location_id' => 2,
                'uuid' => '123e4567-e89b-12d3-a456-426614174001',
            ],
            [
                'payment' => 750.00,
                'payment_date' => '2024-02-10',
                'payment_type' => 'Final Payment',
                'payment_mode' => 'Direct Deposit',
                'cheque_type' => 'Own',
                'cheque_no' => '',
                'cheque_date' => null,
                'is_cheque_realized' => null,
                'account_no' => '1234567890',
                'deposited_date' => '2024-02-11',
                'card_holder_name' => '',
                'card_no' => '',
                'expiry_date' => null,
                'bank_id' => 1,
                'status' => 'Paid',
                'notes' => 'Final payment for invoice #INV003',
                'payment_from' => 'Direct',
                'refunded_from' => null,
                'credit_id' => null,
                'prepared_by' => 3,
                'deposited_to' => null,
                'invoice_id' => 3,
                'sales_order_id' => null,
                'customer_id' => 3,
                'business_type_id' => 2,
                'company_id' => 1,
                'sales_location_id' => 3,
                'uuid' => '123e4567-e89b-12d3-a456-426614174002',
            ],
        ];
        $now = \Carbon\Carbon::now();
        foreach ($invoicePayments as $key => $invoicePayment) {
            $invoicePayments[$key]['created_at'] = $now;
            $invoicePayments[$key]['updated_at'] = $now;
        }

        \App\InvoicePayment::insert($invoicePayments);
    }
}
