<?php

use Illuminate\Database\Seeder;

class SalesordersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sales_order = [
            [
                'order_no' => 'SO0001',
                'ref' => 'REF001',
                'order_date' => '2024-02-01',
                'delivery_date' => '2024-02-10',
                'order_type' => 'Direct',
                'scheduled_date' => null,
                'order_mode' => 'Customer',
                'is_credit_sales' => 'No',
                'is_po_received' => 'Yes',
                'po_no' => 'PO001',
                'po_date' => '2024-01-25',
                'po_file' => 'po001.pdf',
                'terms' => 'Payment due in 30 days',
                'notes' => 'Urgent delivery required',
                'sub_total' => 1500.00,
                'discount' => 100.00,
                'discount_rate' => 10.00,
                'discount_type' => 'Percentage',
                'adjustment' => 50.00,
                'total' => 1450.00,
                'status' => 'Scheduled',
                'delivery_status' => 'Pending',
                'invoice_status' => 'Pending',
                'is_invoiced' => 'No',
                'prepared_by' => 1,
                'approval_status' => 'Pending',
                'approved_by' => null,
                'customer_id' => 1,
                'business_type_id' => 1,
                'company_id' => 1,
                'rep_id' => null,
                'sales_type' => 'Retail',
                'price_book_id' => null,
                'sales_location_id' => 1,
                'gps_lat' => null,
                'gps_long' => null,
                'is_order_printed' => 'No',
                'sales_category' => 'Office',
                'distance' => null,
                'route_id' => null,
                'location_id' => null,
                'is_opining' => 'No',
                'uuid' => 'f41ae1e3-0851-4264-ba5a-139ea9f40c16',
            ],
            [
                'order_no' => 'SO0002',
                'ref' => 'REF002',
                'order_date' => '2024-02-02',
                'delivery_date' => '2024-02-11',
                'order_type' => 'Schedule',
                'scheduled_date' => '2024-02-15',
                'order_mode' => 'Cash',
                'is_credit_sales' => 'Yes',
                'is_po_received' => 'No',
                'po_no' => null,
                'po_date' => null,
                'po_file' => null,
                'terms' => 'Payment due on delivery',
                'notes' => 'Customer requested expedited delivery',
                'sub_total' => 2500.00,
                'discount' => 200.00,
                'discount_rate' => 8.00,
                'discount_type' => 'Percentage',
                'adjustment' => 100.00,
                'total' => 2400.00,
                'status' => 'Draft',
                'delivery_status' => 'Partially Delivered',
                'invoice_status' => 'Partially Invoiced',
                'is_invoiced' => 'No',
                'prepared_by' => 2,
                'approval_status' => 'Approved',
                'approved_by' => 1,
                'customer_id' => 2,
                'business_type_id' => 2,
                'company_id' => 2,
                'rep_id' => 1,
                'sales_type' => 'Wholesale',
                'price_book_id' => 1,
                'sales_location_id' => 2,
                'gps_lat' => '52.5200',
                'gps_long' => '13.4050',
                'is_order_printed' => 'Yes',
                'sales_category' => 'Shop',
                'distance' => 15.2,
                'route_id' => 1,
                'location_id' => 1,
                'is_opining' => 'Yes',
                'uuid' => 'cfed42a5-42c9-4b10-b0f0-1fb3ddae0f67',
            ],
            [
                'order_no' => 'SO0003',
                'ref' => 'REF003',
                'order_date' => '2024-02-03',
                'delivery_date' => '2024-02-12',
                'order_type' => 'Direct',
                'scheduled_date' => null,
                'order_mode' => 'Customer',
                'is_credit_sales' => 'No',
                'is_po_received' => 'Yes',
                'po_no' => 'PO002',
                'po_date' => '2024-01-28',
                'po_file' => 'po002.pdf',
                'terms' => 'Payment due in 15 days',
                'notes' => 'Special packaging required',
                'sub_total' => 1800.00,
                'discount' => 150.00,
                'discount_rate' => 8.33,
                'discount_type' => 'Percentage',
                'adjustment' => 75.00,
                'total' => 1725.00,
                'status' => 'Open',
                'delivery_status' => 'Delivered',
                'invoice_status' => 'Invoiced',
                'is_invoiced' => 'Yes',
                'prepared_by' => 3,
                'approval_status' => 'Approved',
                'approved_by' => 2,
                'customer_id' => 3,
                'business_type_id' => 3,
                'company_id' => 3,
                'rep_id' => 2,
                'sales_type' => 'Distribution',
                'price_book_id' => 2,
                'sales_location_id' => 3,
                'gps_lat' => '48.8566',
                'gps_long' => '2.3522',
                'is_order_printed' => 'No',
                'sales_category' => 'Van',
                'distance' => 25.8,
                'route_id' => 2,
                'location_id' => 2,
                'is_opining' => 'No',
                'uuid' => 'a74b0ebd-1523-40e7-a2ff-943b1e0dc1f7',
            ],
            [
                'order_no' => 'SO0004',
                'ref' => 'REF004',
                'order_date' => '2024-02-04',
                'delivery_date' => '2024-02-13',
                'order_type' => 'Schedule',
                'scheduled_date' => '2024-02-18',
                'order_mode' => 'Cash',
                'is_credit_sales' => 'Yes',
                'is_po_received' => 'No',
                'po_no' => null,
                'po_date' => null,
                'po_file' => null,
                'terms' => 'Payment due on delivery',
                'notes' => 'Requires special handling',
                'sub_total' => 2200.00,
                'discount' => 180.00,
                'discount_rate' => 8.18,
                'discount_type' => 'Percentage',
                'adjustment' => 90.00,
                'total' => 2110.00,
                'status' => 'Closed',
                'delivery_status' => 'Delivered',
                'invoice_status' => 'Invoiced',
                'is_invoiced' => 'Yes',
                'prepared_by' => 4,
                'approval_status' => 'Approved',
                'approved_by' => 1,
                'customer_id' => 2,
                'business_type_id' => 1,
                'company_id' => 4,
                'rep_id' => 3,
                'sales_type' => 'Wholesale',
                'price_book_id' => 3,
                'sales_location_id' => 4,
                'gps_lat' => '51.5074',
                'gps_long' => '-0.1278',
                'is_order_printed' => 'Yes',
                'sales_category' => 'Shop',
                'distance' => 10.5,
                'route_id' => 3,
                'location_id' => 3,
                'is_opining' => 'Yes',
                'uuid' => 'c50e2d1d-03b4-464b-aaba-0622954c3da8',
            ],
            [
                'order_no' => 'SO0005',
                'ref' => 'REF005',
                'order_date' => '2024-02-05',
                'delivery_date' => '2024-02-14',
                'order_type' => 'Direct',
                'scheduled_date' => null,
                'order_mode' => 'Customer',
                'is_credit_sales' => 'No',
                'is_po_received' => 'Yes',
                'po_no' => 'PO003',
                'po_date' => '2024-02-01',
                'po_file' => 'po003.pdf',
                'terms' => 'Payment due in 7 days',
                'notes' => 'Requires expedited shipping',
                'sub_total' => 1900.00,
                'discount' => 120.00,
                'discount_rate' => 6.32,
                'discount_type' => 'Percentage',
                'adjustment' => 80.00,
                'total' => 1900.00,
                'status' => 'Canceled',
                'delivery_status' => 'Canceled',
                'invoice_status' => 'Pending',
                'is_invoiced' => 'No',
                'prepared_by' => 5,
                'approval_status' => 'Rejected',
                'approved_by' => null,
                'customer_id' => 2,
                'business_type_id' => 2,
                'company_id' => 4,
                'rep_id' => 4,
                'sales_type' => 'Distribution',
                'price_book_id' => 4,
                'sales_location_id' => 5,
                'gps_lat' => '40.7128',
                'gps_long' => '-74.0060',
                'is_order_printed' => 'No',
                'sales_category' => 'Van',
                'distance' => 12.3,
                'route_id' => 4,
                'location_id' => 4,
                'is_opining' => 'No',
                'uuid' => '8fb63fc2-b7d8-481f-bf3a-bd0d52e31428',
            ],
        ];

        $now = \Carbon\Carbon::now();
        foreach ($sales_order as $key => $add) {
            $sales_order[$key]['created_at'] = $now;
            $sales_order[$key]['updated_at'] = $now;
        }

        \App\SalesOrder::insert($sales_order);
    }
}
