<?php

use Illuminate\Database\Seeder;

class SalesreturnitemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $salereturnitems = [
            [
                'qty' => '10',
                'type' => 'Stock',
                'sold_rate' => '754.963',
                'returned_rate' => '849.546',
                'returned_amount'=> '1000.00',
                'reason' => 'Color different',
                'sales_return_id' => 1,
                'order_id' => 1,
                'product_id' => 1,
                'returned_to' => 1,
                'route_id' => 1,
                'rep_id' => 1,
                'customer_id' => 1,
                'daily_sale_id' => 1,
                'company_id' => 1,
            ],
            [
                'qty' => '8',
                'type' => 'Stock',
                'sold_rate' => '675.25',
                'returned_rate' => '800.00',
                'returned_amount'=> '640.00',
                'reason' => 'Damaged packaging',
                'sales_return_id' => 2,
                'order_id' => 2,
                'product_id' => 2,
                'returned_to' => 2,
                'route_id' => 2,
                'rep_id' => 2,
                'customer_id' => 1,
                'daily_sale_id' => 2,
                'company_id' => 1,
            ],
            [
                'qty' => '5',
                'type' => 'Stock',
                'sold_rate' => '550.00',
                'returned_rate' => '600.00',
                'returned_amount'=> '300.00',
                'reason' => 'Size mismatch',
                'sales_return_id' => 3,
                'order_id' => 3,
                'product_id' => 3,
                'returned_to' => 3,
                'route_id' => 3,
                'rep_id' => 3,
                'customer_id' => 1,
                'daily_sale_id' => 3,
                'company_id' => 1,
            ],
            [
                'qty' => '12',
                'type' => 'Stock',
                'sold_rate' => '920.00',
                'returned_rate' => '1000.00',
                'returned_amount'=> '1200.00',
                'reason' => 'Functionality issue',
                'sales_return_id' => 4,
                'order_id' => 4,
                'product_id' => 3,
                'returned_to' => 4,
                'route_id' => 4,
                'rep_id' => 4,
                'customer_id' => 1,
                'daily_sale_id' => 4,
                'company_id' => 1,
            ],
            [
                'qty' => '7',
                'type' => 'Stock',
                'sold_rate' => '340.00',
                'returned_rate' => '400.00',
                'returned_amount'=> '280.00',
                'reason' => 'Quality issue',
                'sales_return_id' => 1,
                'order_id' => 1,
                'product_id' => 1,
                'returned_to' => 1,
                'route_id' => 2,
                'rep_id' => 1,
                'customer_id' => 1,
                'daily_sale_id' => 3,
                'company_id' => 1,
            ],
            [
                'qty' => '9',
                'type' => 'Stock',
                'sold_rate' => '430.00',
                'returned_rate' => '500.00',
                'returned_amount'=> '450.00',
                'reason' => 'Faulty components',
                'sales_return_id' => 4,
                'order_id' => 1,
                'product_id' => 3,
                'returned_to' => 2,
                'route_id' => 2,
                'rep_id' => 2,
                'customer_id' => 1,
                'daily_sale_id' => 4,
                'company_id' => 1,
            ],
            [
                'qty' => '15',
                'type' => 'Stock',
                'sold_rate' => '800.00',
                'returned_rate' => '900.00',
                'returned_amount'=> '1200.00',
                'reason' => 'Wrong item shipped',
                'sales_return_id' => 2,
                'order_id' => 2,
                'product_id' => 2,
                'returned_to' => 1,
                'route_id' => 2,
                'rep_id' => 1,
                'customer_id' => 1,
                'daily_sale_id' => 2,
                'company_id' => 1,
            ],
            [
                'qty' => '6',
                'type' => 'Stock',
                'sold_rate' => '600.00',
                'returned_rate' => '700.00',
                'returned_amount'=> '420.00',
                'reason' => 'Scratched surface',
                'sales_return_id' => 2,
                'order_id' => 1,
                'product_id' => 3,
                'returned_to' => 2,
                'route_id' => 2,
                'rep_id' => 1,
                'customer_id' => 1,
                'daily_sale_id' => 3,
                'company_id' => 1,
            ],
            [
                'qty' => '11',
                'type' => 'Stock',
                'sold_rate' => '350.00',
                'returned_rate' => '400.00',
                'returned_amount'=> '440.00',
                'reason' => 'Incorrect color',
                'sales_return_id' => 1,
                'order_id' => 1,
                'product_id' => 2,
                'returned_to' => 1,
                'route_id' => 1,
                'rep_id' => 1,
                'customer_id' => 1,
                'daily_sale_id' => 1,
                'company_id' => 1,
            ],
            [
                'qty' => '8',
                'type' => 'Stock',
                'sold_rate' => '280.00',
                'returned_rate' => '320.00',
                'returned_amount'=> '240.00',
                'reason' => 'Incomplete set',
                'sales_return_id' => 3,
                'order_id' => 2,
                'product_id' => 3,
                'returned_to' => 2,
                'route_id' => 2,
                'rep_id' => 4,
                'customer_id' => 1,
                'daily_sale_id' => 1,
                'company_id' => 1,
            ],
        ];
            $now = \Carbon\Carbon::now();
        foreach ($salereturnitems as $key => $salereturnitem) {
            $salereturnitems[$key]['created_at'] = $now;
            $salereturnitems[$key]['updated_at'] = $now;
        }
        \App\SalesReturnItem::insert($salereturnitems);
    }
}