<?php

use Illuminate\Database\Seeder;

class ShophandoversTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $shophandovers = [
            [
                'date' => '2024-02-12',
                'sales' => '25000.125',
                'cash_sales' => '12500.00',
                'cheque_sales' => '2500.125',
                'deposit_sales' => '1500.00',
                'card_sales' => '6500.00',
                'credit_sales' => '2000.00',
                'total_collect' => '25000.25',
                'cheques_count' => '3',
                'total_expense' => '600.00',
                'allowance' => '2000.00',
                'sales_commission' => '650.00',
                'shortage' => '150.00',
                'excess' => '2.00',
                'staff_id' => 1,
                'notes' => 'Handover entry one',
                'status' => 'Confirmed',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-13',
                'sales' => '30000.00',
                'cash_sales' => '15000.00',
                'cheque_sales' => '3500.00',
                'deposit_sales' => '2000.00',
                'card_sales' => '8000.00',
                'credit_sales' => '4500.00',
                'total_collect' => '33000.00',
                'cheques_count' => '4',
                'total_expense' => '700.00',
                'allowance' => '2200.00',
                'sales_commission' => '700.00',
                'shortage' => '100.00',
                'excess' => '5.00',
                'staff_id' => 1,
                'notes' => 'Handover entry two',
                'status' => 'Pending',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-14',
                'sales' => '28000.00',
                'cash_sales' => '13000.00',
                'cheque_sales' => '4000.00',
                'deposit_sales' => '2500.00',
                'card_sales' => '7000.00',
                'credit_sales' => '4500.00',
                'total_collect' => '31000.00',
                'cheques_count' => '2',
                'total_expense' => '800.00',
                'allowance' => '2500.00',
                'sales_commission' => '600.00',
                'shortage' => '200.00',
                'excess' => '3.00',
                'staff_id' => 1,
                'notes' => 'Handover entry three',
                'status' => 'Confirmed',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-15',
                'sales' => '32000.00',
                'cash_sales' => '16000.00',
                'cheque_sales' => '3500.00',
                'deposit_sales' => '3000.00',
                'card_sales' => '8000.00',
                'credit_sales' => '5500.00',
                'total_collect' => '36500.00',
                'cheques_count' => '5',
                'total_expense' => '900.00',
                'allowance' => '2000.00',
                'sales_commission' => '750.00',
                'shortage' => '50.00',
                'excess' => '1.00',
                'staff_id' => 1,
                'notes' => 'Handover entry four',
                'status' => 'Confirmed',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-16',
                'sales' => '29000.00',
                'cash_sales' => '14000.00',
                'cheque_sales' => '3000.00',
                'deposit_sales' => '2000.00',
                'card_sales' => '7000.00',
                'credit_sales' => '6000.00',
                'total_collect' => '32000.00',
                'cheques_count' => '3',
                'total_expense' => '750.00',
                'allowance' => '1800.00',
                'sales_commission' => '700.00',
                'shortage' => '100.00',
                'excess' => '2.00',
                'staff_id' => 1,
                'notes' => 'Handover entry five',
                'status' => 'Pending',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-17',
                'sales' => '33000.00',
                'cash_sales' => '17000.00',
                'cheque_sales' => '4000.00',
                'deposit_sales' => '2500.00',
                'card_sales' => '7500.00',
                'credit_sales' => '5000.00',
                'total_collect' => '35500.00',
                'cheques_count' => '4',
                'total_expense' => '850.00',
                'allowance' => '2100.00',
                'sales_commission' => '800.00',
                'shortage' => '75.00',
                'excess' => '4.00',
                'staff_id' => 1,
                'notes' => 'Handover entry six',
                'status' => 'Confirmed',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-18',
                'sales' => '28000.00',
                'cash_sales' => '14000.00',
                'cheque_sales' => '3000.00',
                'deposit_sales' => '2000.00',
                'card_sales' => '7500.00',
                'credit_sales' => '5500.00',
                'total_collect' => '32000.00',
                'cheques_count' => '3',
                'total_expense' => '700.00',
                'allowance' => '2000.00',
                'sales_commission' => '750.00',
                'shortage' => '100.00',
                'excess' => '2.00',
                'staff_id' => 1,
                'notes' => 'Handover entry seven',
                'status' => 'Confirmed',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-19',
                'sales' => '31000.00',
                'cash_sales' => '16000.00',
                'cheque_sales' => '3500.00',
                'deposit_sales' => '3000.00',
                'card_sales' => '7000.00',
                'credit_sales' => '5500.00',
                'total_collect' => '35000.00',
                'cheques_count' => '2',
                'total_expense' => '900.00',
                'allowance' => '2500.00',
                'sales_commission' => '700.00',
                'shortage' => '50.00',
                'excess' => '1.00',
                'staff_id' => 1,
                'notes' => 'Handover entry eight',
                'status' => 'Confirmed',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-20',
                'sales' => '33000.00',
                'cash_sales' => '17000.00',
                'cheque_sales' => '4000.00',
                'deposit_sales' => '2500.00',
                'card_sales' => '7500.00',
                'credit_sales' => '5000.00',
                'total_collect' => '36000.00',
                'cheques_count' => '4',
                'total_expense' => '800.00',
                'allowance' => '2100.00',
                'sales_commission' => '800.00',
                'shortage' => '75.00',
                'excess' => '4.00',
                'staff_id' =>1,
                'notes' => 'Handover entry nine',
                'status' => 'Pending',
                'prepared_by' => 1,
                'company_id' => 1
            ],
            [
                'date' => '2024-02-21',
                'sales' => '29000.00',
                'cash_sales' => '14000.00',
                'cheque_sales' => '3000.00',
                'deposit_sales' => '2000.00',
                'card_sales' => '7000.00',
                'credit_sales' => '6000.00',
                'total_collect' => '32000.00',
                'cheques_count' => '3',
                'total_expense' => '750.00',
                'allowance' => '1800.00',
                'sales_commission' => '700.00',
                'shortage' => '100.00',
                'excess' => '2.00',
                'staff_id' => 1,
                'notes' => 'Handover entry ten',
                'status' => 'Confirmed',
                'prepared_by' => 1,
                'company_id' => 1
            ],
        ];
            $now = \Carbon\Carbon::now();
        foreach ($shophandovers as $key => $shophandover) {
            $shophandovers[$key]['created_at'] = $now;
            $shophandovers[$key]['updated_at'] = $now;
        }
        \App\ShopHandover::insert($shophandovers);
    }
}